# Aahanaa (Atibrewa)
# Makefile for Typedef_cast activity!

CC=gcc -std=c99

typedef_cast: typedef_cast.c
	${CC} -o typedef_cast typedef_cast.c

experiment: experiment.c binary_convert.c
	${CC} -o experiment binary_convert.c experiment.c

clean:
	rm -f typedef_cast
